schema_version = "1.0.0"

id = "keyboard_layout_emulation"
version = "1.0.0"
name = "Keyboard Layout Emulation"
tagline = "Emulate QWERTY keyboard shortcuts on non-QWERTY keyboard layouts"
maintainer = "Endor H"
type = "add-on"
website = "https://endorh.github.io/blender-extensions/keyboard-layout-emulation/"
tags = ["User Interface"]

blender_version_min = "4.2.0"
# blender_version_max = ...

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Import/export keyboard layouts/add-on preferences"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/*.md",
]
